/**
 * Exports every widget label/tooltip in a project as a flat text
 * catalog file -- ported from FLTK's `fluid/io/String_Writer.h`/
 * `.cxx` (`fluid::io::write_strings()`). `fluid/io/`'s other four
 * files: `Code_Writer`/`Project_Reader`/`Project_Writer` are this
 * port's own `code_writer.d`/`project_reader.d`/`project_writer.d`
 * (ported earlier, different names -- see `PORTING.md`'s `## Fluid`
 * section); `file_chooser.h`/`.cxx` (the shared `fluid::io::
 * filechooser()` wrapper every FLTK Open/Save/Browse dialog
 * funnels through) is still unported -- a real, separate follow-up.
 *
 * This is the i18n *string-table export* `codeview_panel.fl`'s own
 * doc comment named as a real, deliberate scope cut when that panel
 * was first ported ("no separate i18n string-table export (a `.po`/
 * `.msg` catalog file)... both entire tabs FLTK has simply don't
 * apply here") -- that cut was specifically about *Code View*'s own
 * Header/Strings *tabs*, not about the underlying export capability
 * itself, which is genuinely independent (a one-shot file write, no
 * node<->text-position tracking needed) and is what's ported here,
 * reachable from `gui_main.d`'s own `&File/&Write Strings` menu item
 * instead of a Code View tab (this dialect's Code View only ever had
 * Source/Project tabs to begin with, see that module's own doc
 * comment -- there's no third tab to put this behind).
 *
 * Walks every `WidgetNode` in the project (this port's own tree-
 * shaped `Node`, recursively -- FLTK's own flat doubly-linked-list
 * `Node::next` walk / `Tree::all_widgets()` range are two different
 * FLTK mechanisms for the same "every widget node in document
 * order" result). This already includes every `MenuItem` (`fluid.
 * menu_item_node.MenuItemNode` is a plain `WidgetNode` subclass, no
 * override) -- confirmed, not just assumed, since `code_writer.d`'s own
 * `writeMenuItemLiteral()` wraps menu item labels via
 * `i18nWrap()` too, needing a catalog to actually
 * translate against; `collectWidgets()` itself needs no special-casing for that.
 * Per `I18nSettings.type`:
 *  - `none`: a plain list of raw label/tooltip strings, one per line.
 *  - `gnu`: a minimal `.po`-shaped `msgid "..."` / `msgstr "..."` pair
 *    per string (`msgstr` seeded with the same original text --
 *    FLTK's own file is a *template* for a translator to edit,
 *    not a real po-format tool's smarter output).
 *  - `posix`: a `.msg`-shaped catalog (`$set`/`$quote` header, then
 *    `N "text"` per string, `N` a running 1-based index).
 *
 * Escaping (`writeEscaped()`) is ported byte-for-byte, not codepoint-
 * for-codepoint: FLTK's own `write_escaped_strings()` walks the
 * string as `unsigned char`s and individually `\NNN`-octal-escapes
 * every byte outside 32-126 (plus `"`, `\r`, `\n` specially) --
 * including each individual byte of a multi-byte UTF-8 sequence, not
 * one escape per Unicode codepoint. FLTK's own doc comment
 * acknowledges this as a known, not-yet-fixed limitation ("we should
 * have an option in the project settings to allow utf-8 characters in
 * the output text and not escape them") -- ported faithfully as-is,
 * not corrected, since correcting it would silently diverge from what
 * FLTK's own `.po`/`.msg` output actually looks like today.
 */
module fluid.string_writer;

import std.stdio : File;
import std.format : format;

import fluid.node : Node;
import fluid.widget_node : WidgetNode;
import fluid.i18n : I18nSettings, I18nType;

private void writeEscaped(ref File f, string text)
{
    foreach (ubyte c; cast(immutable(ubyte)[]) text)
    {
        if (c == '\r')
            f.write("\\r");
        else if (c == '\n')
            f.write("\\n");
        else if (c < 32 || c > 126 || c == '"')
            f.writef("\\%03o", cast(int) c);
        else
            f.write(cast(char) c);
    }
}

private void collectWidgets(Node n, ref WidgetNode[] result)
{
    if (auto wn = cast(WidgetNode) n)
        result ~= wn;
    foreach (c; n.children)
        collectWidgets(c, result);
}

/// Writes `filename`, returning `0` on success (matching FLTK's
/// own `fclose()`-return-code-shaped API) or `1` if the file couldn't
/// be opened for writing.
int writeStrings(Node[] roots, I18nSettings i18n, string filename)
{
    File f;
    try
        f = File(filename, "wb");
    catch (Exception e)
        return 1;

    WidgetNode[] widgets;
    foreach (r; roots)
        collectWidgets(r, widgets);

    final switch (i18n.type)
    {
    case I18nType.none:
        f.write("# generated by fldtk fluid\n");
        foreach (wn; widgets)
        {
            if (wn.hasLabel)
            {
                writeEscaped(f, wn.label);
                f.write("\n");
            }
            if (wn.tooltip.length)
            {
                writeEscaped(f, wn.tooltip);
                f.write("\n");
            }
        }
        break;

    case I18nType.gnu:
        f.write("# generated by fldtk fluid\n");
        foreach (wn; widgets)
        {
            if (wn.hasLabel)
            {
                f.write(`msgid "`); writeEscaped(f, wn.label); f.write("\"\n");
                f.write(`msgstr "`); writeEscaped(f, wn.label); f.write("\"\n");
            }
            if (wn.tooltip.length)
            {
                f.write(`msgid "`); writeEscaped(f, wn.tooltip); f.write("\"\n");
                f.write(`msgstr "`); writeEscaped(f, wn.tooltip); f.write("\"\n");
            }
        }
        break;

    case I18nType.posix:
        f.write("$ generated by fldtk fluid\n");
        f.writef("$set %s\n", i18n.posixSet);
        f.write("$quote \"\n");
        int idx = 1;
        foreach (wn; widgets)
        {
            if (wn.hasLabel)
            {
                f.writef("%d \"", idx++);
                writeEscaped(f, wn.label);
                f.write("\"\n");
            }
            if (wn.tooltip.length)
            {
                f.writef("%d \"", idx++);
                writeEscaped(f, wn.tooltip);
                f.write("\"\n");
            }
        }
        break;
    }

    f.close();
    return 0;
}

unittest
{
    import fluid.window_node : WindowNode;
    import std.file : readText, remove, exists, tempDir;
    import std.path : buildPath;
    import std.algorithm : canFind;

    auto win = new WindowNode();
    win.typeName = "Fl_Window";
    win.label = "Hello";
    win.hasLabel = true;

    auto box = new WidgetNode();
    box.typeName = "Fl_Box";
    box.label = "Wor\"ld"; // exercises quote-escaping
    box.hasLabel = true;
    box.tooltip = "A tip";
    win.addChild(box);

    string path = buildPath(tempDir(), "fldtk_string_writer_test.txt");
    scope (exit) if (exists(path)) remove(path);

    I18nSettings none;
    assert(writeStrings([win], none, path) == 0);
    string textNone = readText(path);
    assert(textNone.canFind("Hello\n"));
    assert(textNone.canFind(`Wor\042ld` ~ "\n")); // '"' has no dedicated escape FLTK -- falls into the generic \NNN octal branch (042 octal = '"')
    assert(textNone.canFind("A tip\n"));

    I18nSettings gnu;
    gnu.type = I18nType.gnu;
    assert(writeStrings([win], gnu, path) == 0);
    string textGnu = readText(path);
    assert(textGnu.canFind(`msgid "Hello"`));
    assert(textGnu.canFind(`msgstr "Hello"`));
    assert(textGnu.canFind(`msgid "A tip"`));

    I18nSettings posix;
    posix.type = I18nType.posix;
    posix.posixSet = "1";
    assert(writeStrings([win], posix, path) == 0);
    string textPosix = readText(path);
    assert(textPosix.canFind("$set 1"));
    assert(textPosix.canFind(`1 "Hello"`));
    assert(textPosix.canFind(`2 "Wor\042ld"`));
    assert(textPosix.canFind(`3 "A tip"`));
}

unittest
{
    // Menu item labels get exported into the catalog too,
    // matching `code_writer.d`'s own i18n-wrapping of `writeMenuItem
    // Literal()` -- `collectWidgets()` needs no special-casing for
    // this: `MenuItemNode` is a plain `WidgetNode` subclass (see that
    // module's own doc comment) with no override, so it's already
    // walked generically alongside every other widget the moment its
    // reader attaches it as a normal child in the `Node` tree. This
    // test exists to confirm that positively, not just assume it from
    // the class hierarchy -- and, for POSIX, that the message number a
    // menu item's label gets here lines up with what `code_writer.d`'s
    // own `msgnum_` counter assigns the identical tree (both walk
    // `Node.children` in the same document order, label-then-tooltip
    // per node, so they stay in lockstep without either module knowing
    // about the other).
    import fluid.window_node : WindowNode;
    import fluid.menu_owner_node : MenuOwnerNode;
    import fluid.menu_item_node : MenuItemNode;
    import std.file : readText, remove, exists, tempDir;
    import std.path : buildPath;
    import std.algorithm : canFind;

    auto win = new WindowNode();
    win.typeName = "Fl_Window";
    win.hasLabel = false;

    auto box = new WidgetNode();
    box.typeName = "Fl_Box";
    box.label = "First";
    box.hasLabel = true;
    win.addChild(box);

    auto menu = new MenuOwnerNode();
    menu.typeName = "Fl_Menu_Button";
    win.addChild(menu);

    auto item = new MenuItemNode();
    item.typeName = "MenuItem";
    item.label = "Open";
    item.hasLabel = true;
    menu.addChild(item);

    string path = buildPath(tempDir(), "fldtk_string_writer_menuitem_test.txt");
    scope (exit) if (exists(path)) remove(path);

    I18nSettings posix;
    posix.type = I18nType.posix;
    posix.posixSet = "1";
    assert(writeStrings([win], posix, path) == 0);
    string text = readText(path);
    assert(text.canFind(`1 "First"`));
    assert(text.canFind(`2 "Open"`));
}
